spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/loooSwc/SpringcloudConfig/
          search-paths: source-frame
          default-label: master
server:
  port: 10002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
